//! laipe-streaming — 3-protocol SSE streaming implementations
//!
//! This crate implements the `StreamEvent` producer side for the three LLM
//! protocols laipe supports today:
//!
//! - **OpenAI Chat Completions** (`openai_chat`) — `stream_chat` API
//! - **OpenAI Responses** (`openai_responses`) — `responses` API with
//!   server-sent `output_item.added` / `function_call_arguments.delta` events
//! - **Anthropic Messages** (`anthropic`) — `messages` API with `content_block_*`
//!   / `message_delta` events
//!
//! All three yield a `tokio::sync::mpsc::Receiver<StreamEvent>` whose items
//! are either text chunks or tool-call partials. Consumers (typically a Tauri
//! command or web SSE handler) translate these into the wire format their
//! frontends want.
//!
//! ## Diagnostics
//!
//! Each protocol implementation accepts an optional
//! `Arc<dyn DiagnosticRecorder>` (see `recorder` module). The recorder
//! receives the **exact request bytes** the streaming layer sent, the
//! **raw response byte chunks** as they arrived, and a final
//! `CompletionOutcome`. Consumers that don't want this layer pass
//! `None` (the streaming layer falls back to `NullRecorder`).
//!
//! ## Performance
//!
//! The four anti-stutter countermeasures from the [Locus battle-test] carry
//! over unchanged:
//!
//! 1. `tokio::task::spawn_blocking` isolates SSE byte → JSON parse
//! 2. `mpsc::channel(64)` decouples parse from emit
//! 3. 16ms rAF + 256-char batch on the emit side
//! 4. Identity-stable downstream state (consumer reuses the same buffer)
//!
//! [Locus battle-test]: https://github.com/amostalong/Locus
//!
//! See `docs/STREAMING.md` for the protocol details and
//! `docs/TOOL_CALLING.md` for cross-protocol tool schema translation.

#![doc(html_root_url = "https://docs.rs/laipe-streaming/0.1.0")]

pub mod anthropic;
pub mod openai_chat;
pub mod openai_responses;
pub mod recorder;
pub mod sse;
pub mod test;
pub mod throttle;

use async_trait::async_trait;
use laipe_core::error::ChatErrorKind;
use laipe_core::types::{ApiFormat, ChatMessage, ProviderConfig, StreamEvent};
use std::sync::Arc;
use thiserror::Error;
use tokio::sync::mpsc;

pub use recorder::{
    redact_request_bytes, CompletionOutcome, DiagnosticRecorder, FileRecorder, NullRecorder,
    RecordingContext,
};
pub use test::{params_from_config, test_provider};

/// Convenience alias for `Result<T, StreamError>`.
pub type StreamResult<T> = std::result::Result<T, StreamError>;

/// Errors raised by streaming implementations. Mid-stream errors after the
/// stream has opened are surfaced as `StreamEvent::Error` instead.
#[derive(Debug, Error)]
pub enum StreamError {
    /// HTTP-level error (connect, TLS, timeout)
    #[error("HTTP error: {0}")]
    Http(#[from] reqwest::Error),

    /// Underlying tokio task / IO error
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),

    /// JSON deserialize failure during SSE parse
    #[error("JSON parse error: {0}")]
    Json(#[from] serde_json::Error),

    /// Upstream returned a non-2xx status with a body
    #[error("upstream returned {status}: {body_preview}")]
    Upstream {
        kind: ChatErrorKind,
        status: u16,
        body_preview: String,
    },

    /// Anything else — surfaced as-is
    #[error("{0}")]
    Other(String),
}

/// Trait every protocol implementation satisfies.
///
/// To add a new LLM protocol, implement this trait and arm in [`pick`].
/// The returned `Receiver<StreamEvent>` is consumed by a Tauri command
/// (or any other async consumer) and translated to the wire format the
/// caller wants.
///
/// ## Diagnostic recorder
///
/// `recorder` is the **only** place where the streaming layer can
/// observe both the exact outgoing request bytes and the raw incoming
/// response chunks. Implementations must call:
///
/// 1. `recorder.record_request(&ctx, body_bytes)` once, before the
///    HTTP POST. `body_bytes` should be the **exact serialized
///    request** the implementation sent (caller is responsible for
///    any pre-redaction; see `redact_request_bytes`).
/// 2. `recorder.record_response_chunk(&ctx, &bytes)` for every
///    network-level byte chunk from `resp.bytes_stream()`.
/// 3. `recorder.record_completion(&ctx, outcome)` once, when the
///    round is over (Done / Error / Cancelled / Pre-stream failure).
///
/// `ctx.id` is generated by the implementation; it ties the three
/// callbacks together (the protocol impl threads it through the
/// `tokio::spawn` that drains the byte stream).
///
/// Implementations that do not want diagnostics receive a
/// `NullRecorder` (the default the blanket `StreamChatDispatch`
/// impl uses when the caller passes `None`).
#[async_trait]
pub trait StreamChat {
    /// Run a chat completion. The returned `Receiver` yields `StreamEvent`
    /// items until the upstream closes, errors, or the consumer drops it.
    ///
    /// Pre-stream errors (connect, TLS, 4xx/5xx) come back as
    /// `Err(StreamError)`. Mid-stream errors come through the receiver as
    /// `StreamEvent::Error`.
    async fn run(
        &self,
        cfg: &ProviderConfig,
        messages: &[ChatMessage],
        tools: Option<&[laipe_core::ToolDefinition]>,
        recorder: Arc<dyn DiagnosticRecorder>,
        ctx: &RecordingContext,
    ) -> Result<mpsc::Receiver<StreamEvent>, StreamError>;
}

/// Classify an upstream non-2xx response into a `StreamError` with the right
/// `ChatErrorKind`. Public so the three protocol implementations share it.
pub fn classify_upstream_error(status: u16, body: &str) -> StreamError {
    let kind = match status {
        401 | 403 => ChatErrorKind::Auth,
        404 => ChatErrorKind::ModelNotFound,
        429 => ChatErrorKind::RateLimit,
        500..=599 => ChatErrorKind::ServerError,
        400..=499 => ChatErrorKind::BadRequest,
        _ => ChatErrorKind::Unknown,
    };
    let body_preview = body.chars().take(800).collect::<String>();
    StreamError::Upstream {
        kind,
        status,
        body_preview,
    }
}

/// Map a reqwest error into a `StreamError` carrying any upstream status
/// it managed to read.
pub fn map_reqwest_error(e: reqwest::Error) -> StreamError {
    if let Some(status) = e.status() {
        return classify_upstream_error(status.as_u16(), &e.to_string());
    }
    StreamError::Other(e.to_string())
}

/// Pick a streaming implementation from an `ApiFormat`.
///
/// Single dispatch point: returns a `'static` reference to the dispatcher
/// for the requested protocol. To add a new protocol, add a new variant to
/// `ApiFormat` and arm in the `match` below.
pub fn pick(fmt: ApiFormat) -> &'static dyn StreamChatDispatch {
    use ApiFormat::*;
    match fmt {
        OpenAiChat => &openai_chat::OpenAiChatStreamer,
        OpenAiResponses => &openai_responses::OpenAiResponsesStreamer,
        Anthropic => &anthropic::AnthropicStreamer,
    }
}

/// Type-erased dispatcher so the consumer doesn't have to thread
/// `async_trait` generics through every call site. Auto-impl'd for every
/// `T: StreamChat + Send + Sync`. Use [`pick`] to get one.
#[async_trait]
pub trait StreamChatDispatch: Send + Sync {
    async fn dispatch(
        &self,
        cfg: &ProviderConfig,
        messages: &[ChatMessage],
        tools: Option<&[laipe_core::ToolDefinition]>,
        recorder: Option<Arc<dyn DiagnosticRecorder>>,
        ctx: &RecordingContext,
    ) -> Result<mpsc::Receiver<StreamEvent>, StreamError>;
}

#[async_trait]
impl<T: StreamChat + Send + Sync> StreamChatDispatch for T {
    async fn dispatch(
        &self,
        cfg: &ProviderConfig,
        messages: &[ChatMessage],
        tools: Option<&[laipe_core::ToolDefinition]>,
        recorder: Option<Arc<dyn DiagnosticRecorder>>,
        ctx: &RecordingContext,
    ) -> Result<mpsc::Receiver<StreamEvent>, StreamError> {
        // Default to NullRecorder when the caller passes None. This keeps
        // the protocol impls free of `Option<Arc<...>>` plumbing.
        let recorder: Arc<dyn DiagnosticRecorder> =
            recorder.unwrap_or_else(|| Arc::new(NullRecorder));
        StreamChat::run(self, cfg, messages, tools, recorder, ctx).await
    }
}
